image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup FSL + ANTs
    command: |
      # Update and install dependencies
      sudo apt update && sudo apt install -y wget bzip2 python3 python3-pip

      # Workaround: symlink lbzip2 to bzip2
      sudo ln -s /bin/bzip2 /usr/local/bin/lbzip2 || true

      # Install FSL
      wget https://fsl.fmrib.ox.ac.uk/fsldownloads/fslinstaller.py
      python3 fslinstaller.py <<EOF
yes
full
EOF

      # Configure environment variables for FSL
      echo 'export FSLDIR=/usr/local/fsl' >> ~/.bashrc
      echo 'source $FSLDIR/etc/fslconf/fsl.sh' >> ~/.bashrc
      echo 'export PATH=$FSLDIR/bin:$PATH' >> ~/.bashrc
      source ~/.bashrc

      # Install Miniconda
      wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      bash miniconda.sh -b -p $HOME/miniconda
      eval "$($HOME/miniconda/bin/conda shell.bash hook)"

      # Create conda env for ANTs
      conda create -n ants -c conda-forge ants -y

      echo "✅ Setup complete. Run 'conda activate ants' to use ANTs"
