image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup FSL + ANTs
    init: |
      # Install ANTs
      wget https://downloads.apache.org/ant/binaries/apache-ant-1.10.14-bin.tar.gz
      tar -xvzf apache-ant-1.10.14-bin.tar.gz
      sudo mv apache-ant-1.10.14 /opt/ant
      echo 'export ANT_HOME=/opt/ant' | sudo tee -a /etc/profile
      echo 'export PATH=$ANT_HOME/bin:$PATH' | sudo tee -a /etc/profile
      source /etc/profile

      # Install FSL
      # Download installer
      curl -sSL https://fsl.fmrib.ox.ac.uk/fsldownloads/fslinstaller.py -o fslinstaller.py

      # Run in headless mode (no GUI)
      python fslinstaller.py --dest=/usr/local/fsl

      echo "FSLDIR=/usr/local/fsl" >> ~/.bashrc
      echo ". ${FSLDIR}/etc/fslconf/fsl.sh" >> ~/.bashrc
      echo "export FSLDIR" >> ~/.bashrc
      source ~/.bashrc
    command: |
      echo "✅ FSL and ANTs installed"
      ant -version
      bet -h       # Brain Extraction Tool
      fslmaths -h  # FSL maths
      fast -h      # Segmentation
      flirt -version
      bash
